### ISSUE TITLE
Object instead of two arguments passed as constructor

### ISSUE THREAD

**Issue by sabbio93** [ale8193/doc-node#11]
https://github.com/ale8193/doc-node/blob/d7f84b19c46989093165eb5c1a4c27b4a9d690e3/src/model/Backup.js#L19-L26
What is the advantage of passing data object instead of two basic type arguments?
Moreover is not clear what is options and how to use them, neither if is a general requirement for all backups or only for backups in WebDAV.

**Comment by ale8193** [comment]
1. the advantage of passing data object is for future integration, because maybe we will need more parameters
2. options same as for data in future could be integrated with more options, now is used only to set the separator that will be used in the `toString` method. So it is not only for webdav, but it can be used in any other destination to create the name of the backup file
